# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@rules_rpm//rpm:defs.bzl", "rpm_package")
load("//:lifecycle_helpers.bzl", "lifecycle_py_flatbuffer_library")

lifecycle_py_flatbuffer_library()

rpm_package(
    name = "lola-demo",
    binaries = [
        "@score_communication//score/mw/com/example/ipc_bridge:ipc_bridge_cpp",
    ],
    config_dir = "/etc/lola",
    data = [
        "@score_communication//score/mw/com/example/ipc_bridge:etc/mw_com_config.json",
    ],
    data_dir = "/usr/share/lola/examples",
    description = "LOLA middleware communication libraries for development including core communication, configuration components, and example client/server binaries for testing",
    libraries = [
        "@score_communication//score/mw/com:com",
        "@score_communication//score/mw/com:config_schema",
    ],
    summary = "LOLA Demo",
    version = "1.0.0",
)

rpm_package(
    name = "lifecycle-demo",
    binaries = [
        "@score_lifecycle_health//src/launch_manager_daemon:launch_manager",
        "@score_lifecycle_health//examples/cpp_supervised_app:cpp_supervised_app",
        "@score_lifecycle_health//examples/cpp_lifecycle_app:cpp_lifecycle_app",
        "@score_lifecycle_health//examples/rust_supervised_app:rust_supervised_app",
        "@score_lifecycle_health//examples/control_application:control_daemon",
        "@score_lifecycle_health//examples/control_application:lmcontrol",
    ],
    config_dir = "/etc/score-lifecycle-health",
    description = "Eclipse SCORE Lifecycle Health components including Health Monitor and Launch Manager.",
    libraries = [
        "@score_lifecycle_health//src/launch_manager_daemon/process_state_client_lib:process_state_client",
        "@score_lifecycle_health//src/launch_manager_daemon/lifecycle_client_lib:lifecycle_client",
        "@score_lifecycle_health//src/control_client_lib:control_client_lib",
        "@score_lifecycle_health//src/launch_manager_daemon/health_monitor_lib:hm_shared_lib",
    ],
    summary = "Eclipse SCORE Lifecycle Health Demo",
    version = "1.0.0",
)
